### PR TITLE
cleanup and ci

### PR DESCRIPTION
**Pull request by xf8b**

### CODE REVIEW

**Comment by xf8b** [comment]
DO NOT MERGE YET - ADDING CI

**Comment by xf8b** [comment]
ok done you can merge

**Comment by TheOnlyTails** [comment]
First of all, thank you very much for helping me improve the quality of this repo!
Can you please just describe what exactly you added/changed here?

**Comment by TheOnlyTails** [comment]
Ok - I went through all of the changes.
YOU ARE A LEGEND. The code is basically improved in every single way.
The only thing I would like you to explain is how exactly the CI works.

**Pull request merged**
